[package]
name = "rust-basic-chat-application"
version = "0.1.0"
edition = "2024"

[dependencies]
async-std = "1.13.1"
serde = { version = "1.0.228", features = ["derive", "rc"] }
serde_json = "1.0.145"
tokio = "1.48.0"
